name: Run Benchmark on Change

on:
  pull_request:
    paths: 
      - 'langs/**/*'
      - '.github/workflows/benchmark_on_change.yml'
      - 'benchmark.py'
      - 'run_on_changes.py'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    permissions:
      pull-requests: read

    strategy:
      fail-fast: false
      matrix:
        lang: 
          - c-plus-plus
          - c-sharp
          - fortran
          - go
          - java
          - kotlin
          - lua
          - node
          - perl
          - php
          - python
          - ruby
          - rust
          - swift

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            !**/*.md
            !**/*.yml
            !**/*.json

      - name: Pull Docker image
        if: ${{ steps.changed-files.outputs.any_changed == 'true' && contains(steps.changed-files.outputs.all_changed_files, format('langs/{0}/', matrix.lang)) }}
        run: docker compose pull ${{ matrix.lang }}

      - name: Run benchmarks for changed files
        if: ${{ steps.changed-files.outputs.any_changed == 'true' && contains(steps.changed-files.outputs.all_changed_files, format('langs/{0}/', matrix.lang)) }}
        run: |
          docker compose run ${{ matrix.lang }} python3 ./run_on_changes.py ${{ steps.changed-files.outputs.all_changed_files }}