name: Run Benchmark on Change

on:
  pull_request:
    branches:
      - master


jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 2

      - name: Pull Docker image
        run: docker-compose pull benchmark

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            !**/*.md
            !**/*.yml
            !**/*.json

      - name: Run benchmarks for changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          docker-compose run benchmark python3 ./run_on_changes.py $ALL_CHANGED_FILES