name: Run Benchmark on Change

on:
  pull_request:
    paths: 
      - 'langs/**/*'
      - '.github/workflows/benchmark_on_change.yml'
      - 'benchmark.py'
      - 'run_on_changes.py'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    permissions:
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Pull Docker image
        run: docker compose pull benchmark

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            !**/*.md
            !**/*.yml
            !**/*.json

      - name: Run benchmarks for changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          docker compose run benchmark python3 ./run_on_changes.py ${{ steps.changed-files.outputs.all_changed_files }}